### ISSUE TITLE
LaTeX to mathML: semantic whitespace removed

### ISSUE THREAD

**Issue by lnelson2382** [tarleb/querverweis#2]
** Overview **
Using this filter to convert LaTeX to mathML, some semantic whitespace inside \begin{equation} environments with \label items is removed

** Sample Input File "label.tex"
```
\section{Section} \label{section}
\begin{equation}
    y^2 = \omega x^2
    \label{eq:sample}
\end{equation}
This is Equation~\ref{eq:sample}, in Section~\ref{section}.
The following equation doesn't have the same issue:
\begin{equation}
    y^2 = \omega x^2
\end{equation}
```

** Pandoc command**
pandoc -f latex -t html --mathml --lua-filter ~/querverweis.lua label.tex -o label.html

** Error message **
```
[WARNING] Could not convert TeX math y^2=\omegax^2, rendering as TeX:
  y^2=\omegax^2
             ^
unexpected control sequence \omegax
expecting "%", "\\label", "\\tag", "\\nonumber", whitespace or "\\allowbreak"
```

** Other Notes **
I downloaded the file `querverweis.lua` from the repository and put it in my home directory; I'm not sure if this is the intended way to run the filter, but other than this whitespace issue it seems to give the expected results.

**Comment by tarleb** [comment]
Many thanks a lot for the report and for testing this filter!

The bug should be fixed now.

You can also "install" the filter by moving it to `$HOME/.local/share/pandoc/filters`. (Or to the "user directory" folder mentioned in the output of `pandoc -v`). You might have to create that directory.

**Comment by tarleb** [comment]
Side note: I'm also working on another filter to support equation numbering, see [rivnjannja](https://github.com/tarleb/rivnjannja), maybe you find that one useful, too.
